// Mocks generated by Mockito 5.2.0 from annotations
// in movis/test/application/movie_info/movie_info_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movis/core/error/failures.dart' as _i5;
import 'package:movis/domain/movie_info/movie_info.dart' as _i6;
import 'package:movis/infrastructure/movie_info/movie_info_repository_impl.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [MovieInfoRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieInfoRepositoryImpl extends _i1.Mock
    implements _i3.MovieInfoRepositoryImpl {
  MockMovieInfoRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.TheMovieDBFailure, _i6.MovieInfo>> getMovieInfo(
          int? id, String? lang) =>
      (super.noSuchMethod(Invocation.method(#getMovieInfo, [id, lang]),
          returnValue:
              Future<_i2.Either<_i5.TheMovieDBFailure, _i6.MovieInfo>>.value(
                  _FakeEither_0<_i5.TheMovieDBFailure, _i6.MovieInfo>())) as _i4
          .Future<_i2.Either<_i5.TheMovieDBFailure, _i6.MovieInfo>>);
}
