// Mocks generated by Mockito 5.2.0 from annotations
// in movis/test/infrastructure/movies_list/movies_list_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movis/infrastructure/movies_list/movie_dto.dart' as _i4;
import 'package:movis/infrastructure/movies_list/movies_list_remote_data_source.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [MoviesListRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesListRemoteDataSourceImpl extends _i1.Mock
    implements _i2.MoviesListRemoteDataSourceImpl {
  MockMoviesListRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MovieDto>> getPopularMovies() =>
      (super.noSuchMethod(Invocation.method(#getPopularMovies, []),
              returnValue: Future<List<_i4.MovieDto>>.value(<_i4.MovieDto>[]))
          as _i3.Future<List<_i4.MovieDto>>);
}
